### ISSUE TITLE
Check by name AND size - make radios into checkboxes

### ISSUE THREAD

**Issue by MrJake222** [qarmin/czkawka#376] opened 2021-06-14 10:21 UTC
Why can't I check my files for matching names and sizes? I'd make sense to filter out potential duplicates by name, and then run a second check for size. Hashes take too long on my library of files.

**Comment by Chaiavi** [comment] 2021-08-16 08:32
I second this request

**Comment by qarmin** [comment] 2021-11-25 10:01
Duplicate of #298

**Closed by qarmin** 2021-11-25 10:01 UTC
