### ISSUE TITLE
paste text crashed the application on Windows

### ISSUE THREAD

**Issue by mio-19** [qarmin/czkawka#1170] opened 2023-12-28 10:14 UTC
**Bug Description**
...

**Steps to reproduce:**
1. Search for duplicated
2. Select -> custom
3. copy a path and paste to path input box

**Terminal output** (optional):

Lost the terminal output

<details>
<summary>Debug log</summary>

```

<!--
Add terminal output only if needed - if there are some errors or warnings or you have performance/freeze issues.  
Very helpful in this situation will be logs from czkawka run with RUST_LOG environment variable set e.g. 
`RUST_LOG=debug ./czkawka` or `flatpak run --env=RUST_LOG=debug com.github.qarmin.czkawka` if you use flatpak, which will print more detailed info about executed function.
-->

```

</details>

**System**

- Czkawka version: 6.1.0 gui_console
- OS version: Windows 11

**Comment by MikeS159** [comment] 2023-12-30 10:24
Can confirm I have also seen this. Pasting valid directories into manual add. I have also seen it in the custom selection section pasting regex in. Sometimes it crashes the program, sometimes it doesn't.

**Comment by qarmin** [comment] 2024-01-14 13:50
Duplicate of https://github.com/qarmin/czkawka/issues/1044

This problem is/will be fixed in new GUI

**Closed by qarmin** 2024-01-14 13:50 UTC
Labels: bug
