### ISSUE TITLE
Crash when pasting a path in custom select > Path

### ISSUE THREAD

**Issue by Topspap** [qarmin/czkawka#1283] opened 2024-05-13 14:53 UTC
**Bug Description**
When pasting a path in custom select by path the app crash and close, and i lost hours of duplicate scan (It happen 3 times)
I did save the search result, how can I import it to avoid re-scan ? 

**Steps to reproduce:**
Normally after finishing a scan and try to custom select by path, when pressing Ctrl + V to past the folder path it immediately crash.
Maybe because the result has thousands of duplicate files.

**Terminal output** (optional):
I'm using the GUI (czkawka_gui)

**System**
Windows 10 Pro
- Czkawka version: Latest [7.0.0]
- OS version: Windows 10 Pro
- Installation method: "windows_czkawka_gui_gtk_46"

**Comment by elgatobavaria** [comment] 2024-06-15 18:31
@Topspap I see the same issue to on WIN 11.

**Comment by qarmin** [comment] 2024-09-30 17:48
Duplicate of https://github.com/qarmin/czkawka/issues/967

**Closed by qarmin** 2024-09-30 17:48 UTC
Labels: bug
