### ISSUE TITLE
Select functions not working

### ISSUE THREAD

**Issue by David72645** [qarmin/czkawka#1205] opened 2024-02-04 01:23 UTC
### Discussed in https://github.com/qarmin/czkawka/discussions/950

<div type='discussions-op-text'>

<sup>Originally posted by **Stewartgg32** March 18, 2023</sup>
Just installed the latest version on mac and am unable to use any of the select functions. 

I am sure it is a user issue but I am unable to find any way to get them to work and I have searched this board for an answer or similar issue with no luck. . 

When I select any option in that list it does nothing. I am able to select one by one. Thanks in advance. 

![image](https://user-images.githubusercontent.com/128245057/226119097-87879a54-ec06-494b-baec-7c3f3f02e887.png)
</div>

**Comment by David72645** [comment] 2024-02-04 01:24
Please help. Can't use select tool. Thanks.

**Comment by qarmin** [comment] 2024-02-04 13:04
Duplicate of https://github.com/qarmin/czkawka/issues/979, this is gtk bug and I don't think that it will be fixed soon.

New gui currently not have ability to select automatically entries, but it will have before 1.0 version

**Closed by qarmin** 2024-02-04 13:04 UTC
