### ISSUE TITLE
AppImage doesn't work on Arch Linux

### ISSUE THREAD

**Issue by guihkx** [qarmin/czkawka#299] opened 2021-03-26 14:47 UTC
Probably not that big of an issue since czkawka is available in the AUR, but reporting it nonetheless:

```
$ ./linux_czkawka_gui-v3.0.0.AppImage
/tmp/.mount_linux_xjhR0t/AppRun.wrapped: symbol lookup error: /usr/lib/libpangoft2-1.0.so.0: undefined symbol: g_task_set_name
```

**Comment by guihkx** [comment] 2021-04-08 07:25
Just downloaded the AppImage artifact [from this build](https://github.com/qarmin/czkawka/runs/2244843736), and now Czkawka runs as expected on Arch.

I guess this can be closed once a new release is available.

**Comment by X0rg** [comment] 2021-04-09 20:17
Upstream PR that fixes the issue: linuxdeploy/linuxdeploy-plugin-gtk#15
Unfortunately, I will need to find an other fix, because it breaks GIO according to linuxdeploy/linuxdeploy-plugin-gtk#16.
In other words, the issue is not totally fixed yet.

**Comment by X0rg** [comment] 2021-04-10 18:52
linuxdeploy/linuxdeploy-plugin-gtk#18 merged upstream, it should solve your issue.

**Comment by guihkx** [comment] 2021-04-10 19:19
Awesome, thanks!

I'll give it a test as soon as a new commit is pushed. Although, I think it'd be better if a new AppImage for release v3.0.0 was published as well.

@qarmin Is this feasible?

**Comment by qarmin** [comment] 2021-04-11 06:19
Action - https://github.com/qarmin/czkawka/actions/runs/736595169
Appimage binary - https://github.com/qarmin/czkawka/suites/2465741639/artifacts/52993743

**Comment by guihkx** [comment] 2021-04-11 07:25
@qarmin Yup, it's working now!

You can close this if you want and, if possible, upload a working AppImage for v3.0.0 as well.

Thank you guys

**Comment by qarmin** [comment] 2021-05-08 20:00
Closing since I will release 3.1.0 version in next hours

**Closed by qarmin** 2021-05-08 20:00 UTC
Labels: bug
