### ISSUE TITLE
Confirmation when deleting all files in group

### ISSUE THREAD

**Issue by lcenchew** [qarmin/czkawka#385] opened 2021-06-29 05:33 UTC
Scenario:

Options `Show confirm dialog when deleting all files in group` is selected

```
Group 1:
file1-1
file1-2
file1-3
Group 2:
file2-1
file2-2
```

Select all Group 2
```
Group 1:
file1-1
file1-2
file1-3
Group 2:
file2-1 = select
file2-2 = select
```

`Delete`

Files are deleted without warning.

Using macOS 10.15

**Comment by git-brownbear** [comment] 2021-07-10 00:20
Also on Debian 11, Version 3.1.0

**Comment by git-brownbear** [comment] 2021-07-10 08:11
Also on Debian 11 with version 3.0.0.
It's strange because it worked with 2 single identical files in one folder yesterday but not now with 5 folders and "26177 duplicates files in 19653 groups which took 26.65 GiB".

**Comment by qarmin** [comment] 2021-07-16 08:43
Can anyone reproduce it with the latest version from "Actions"?

https://github.com/qarmin/czkawka/actions

I tried to reproduce it, but looks that during rewriting code I accidentally fixed this

**Comment by qarmin** [comment] 2021-08-15 13:07
This should be fixed
Please reopen if this is not fully fixed

**Closed by qarmin** 2021-08-15 13:07 UTC
Labels: next version
