### ISSUE TITLE
Windows czkawka_gui (version 6.0.0) fails to launch or start up.

### ISSUE THREAD

**Issue by victornavorskie** [qarmin/czkawka#990] opened 2023-06-11 08:31 UTC
I attempted to use the new version of Windows_czkawka_gui, but it failed to open. Subsequently, I tried launching version 5.1.0, which is still functional. Additionally, the antivirus software is disabled. 

Furthermore, please consider adding an icon to czkawka_gui :)

**Comment by qarmin** [comment] 2023-06-11 09:23
Duplicate of  #989

**Closed by qarmin** 2023-06-11 09:23 UTC
