### ISSUE TITLE
empty directories aren't detected, if any parent starts with a dot

### ISSUE THREAD

**Issue by thomas725** [qarmin/czkawka#1158] opened 2023-12-15 22:39 UTC
**Bug Description**
...

**Steps to reproduce:**
have empty directories within an ext4 filesystem below the scanned folder, where one of the parents no matter if above scanned folder or between empty child and scanned folder, it won't be found / listed in a scan for empty folders.

In contrast, empty folders that don't have a parent starting with dot are found, and correctly filtered so only the highest parent that contains nothing but other empty folders is listed without any of it's children.

**System**

- Czkawka version: 6.1.0 gui (installed via AUR)
- OS version: Manjaro (running release 2023-12-15)

**Comment by qarmin** [comment] 2023-12-16 07:08
Cannot reproduce with cli

![image](https://github.com/qarmin/czkawka/assets/41945903/a89722dd-034b-4da9-b606-f0b5fa5a0a35)

Also cannot reproduce problem with gui

can you show folder/file structure that causes problems?

**Comment by thomas725** [comment] 2023-12-16 07:09
ah maybe it's caused by to deep folder structures instead, now I have another example where no dot is involved, that was just my first guess...

**Comment by qarmin** [comment] 2023-12-16 07:22
You are using gui or cli?
Cli by default not excludes any folders, so results should be clearer.
Gui disables by default multiple folders by exact name and also by wildcard

**Comment by thomas725** [comment] 2023-12-16 07:48
I'm using GUI, but I removed that list and it doesn't match any of the 11 folder involved.
I guess I can try using CLI and see if the results differ, give me a minute.

**Comment by thomas725** [comment] 2023-12-16 08:04
okey so there's definitely a difference between cli & gui that's not explainable by that default "Excluded items" list that the GUI displays (and allows to empty but restores on every restart) = `*/.git/*,*/node_modules/*,*/lost+found/*,*/Trash/*,*/.Trash-*/*,*/snap/*,/home/*/.cache/*`

I have a disk mount = `/run/media/user/UUID/`

Running this `czkawka_cli empty-folders -d .` when the working dir is that disk mount, It gives me those 2 folders:
/run/media/user/UUID/1/2/3/4
/run/media/user/UUID/1/2/3/5

The gui gives an empty result when scanning for empty folders instead.

**Comment by qarmin** [comment] 2023-12-19 10:28
It's not really possible
Currently, the list contains a few very basic items that most users wouldn't want to remove accidentally.

**Comment by qarmin** [comment] 2024-01-14 13:45
Closing since this is expected behavior and can be easily adjusted in gui settings

**Closed by qarmin** 2024-01-14 13:45 UTC
Labels: bug
