### ISSUE TITLE
Cannot build on windows 10 using cargo install

### ISSUE THREAD

**Issue by skreimeyer** [qarmin/czkawka#342] opened 2021-05-13 22:58 UTC
What I did:
`C:\Users\xxx> cargo install czkawka_gui`
What I'm using:
```
Caption                 : Microsoft Windows 10 Pro
InstallDate             : 3/12/2021 9:07:42 PM
ServicePackMajorVersion : 0
OSArchitecture          : 64-bit
xxx
```
What I got:
```
error[E0463]: can't find crate for `strum_macros`
   --> C:\Users\xxx\.cargo\registry\src\github.com-1ecc6299db9ec823\system-deps-1.3.2\src\lib.rs:117:5
    |
117 | use strum_macros::{EnumIter, EnumString};
    |     ^^^^^^^^^^^^ can't find crate

error: aborting due to previous error

For more information about this error, try `rustc --explain E0463`.
error: could not compile `system-deps`
```

**Comment by qarmin** [comment] 2021-05-16 17:31
Cross compilation from Linux to Windows works fine, but I never tried to compile it entirely on Windows, so such things may happen.
Looks that problem is caused by system-deps 1.3.2 library, but the newest is in crates 3.1.1 version, so probably after updating gtk-rs this should be fixed(still I don't know when new version will be available)

**Comment by qarmin** [comment] 2021-11-25 09:54
This was fixed in upstream gtk crate

**Closed by qarmin** 2021-11-25 09:54 UTC
