### ISSUE TITLE
Results window should have the option to go to file location on disk

### ISSUE THREAD

**Issue by Chaiavi** [qarmin/czkawka#421] opened 2021-08-16 08:53 UTC
Currently, when double clicking on the result of the duplicate files, It runs the file with the current windows association.

I would like to have an option to open the file explorer on the path of the file

**Comment by qarmin** [comment] 2021-08-16 09:18
Duplicate of https://github.com/qarmin/czkawka/issues/92

For now clicking twice with right mou

**Closed** 2021-08-16 09:18 UTC

**Comment by Chaiavi** [comment] 2021-08-16 09:20
Thanks
