### ISSUE TITLE
Is it possible to add the ability to right-click to open the folder where the selected file is located? 

### ISSUE THREAD

**Issue by Lisland2032** [qarmin/czkawka#1223] opened 2024-02-23 05:19 UTC
**Feature Description**
...
This makes it easy to see and delete some duplicate folders.
windows UI

**Comment by qarmin** [comment] 2024-02-23 06:18
Duplicate of https://github.com/qarmin/czkawka/issues/684

It is possible to open folder
- Czkawka gui - double right click on record
- Krokeit - single right click on record

**Closed by qarmin** 2024-02-23 06:18 UTC
Labels: enhancement
