### ISSUE TITLE
support for delete key on windows

### ISSUE THREAD

**Issue by bbodenmiller** [qarmin/czkawka#372] opened 2021-06-01 07:30 UTC
Please add support for deleting items using delete key on keyboard when using windows

**Comment by adsick** [comment] 2021-06-17 21:40
I personally find it a good idea too.

**Comment by qarmin** [comment] 2021-06-18 05:07
I have no idea why this works on Linux but not in Windows.

If anyone want to check at which keycode is recognized windows delete key, then it is enough to put between `println!(button_number)`
https://github.com/qarmin/czkawka/blob/2cc4ae33452bf42e1ab6106226b57f39a02ab426/czkawka_gui/src/initialize_gui.rs#L86-L88

**Comment by qarmin** [comment] 2021-11-25 10:01
Duplicate of #306
Since I don't use Windows, checking what exactly button is used in Windows would be helpful

**Closed by qarmin** 2021-11-25 10:01 UTC
