### ISSUE TITLE
Crashes when manually adding a directory

### ISSUE THREAD

**Issue by wssddc** [qarmin/czkawka#1273] opened 2024-04-28 03:29 UTC
**Bug Description**
When pasting a directory path into the manual add screen, the program will often, but not always, crash.

**Steps to reproduce:**
Select manual add.  Paste a directory path with ctrl-v.  Program crashes and pasted text is not displayed.  (If it is displayed, the program does not crash.)

<details>
<summary>Debug log</summary>
Faulting application name: czkawka_gui.exe, version: 0.0.0.0, time stamp: 0x00000000
Faulting module name: libgtk-4-1.dll, version: 4.6.3.0, time stamp: 0x00000000
Exception code: 0xc0000005
Fault offset: 0x00000000003dccf7
Faulting process id: 0x314c
Faulting application start time: 0x01da991aa838048d
Faulting application path: C:\App\Czkawka\czkawka_gui.exe
Faulting module path: C:\App\Czkawka\libgtk-4-1.dll
Report Id: 70a6112f-9dd0-40ba-909d-2ad2192e6dd5
Faulting package full name: 
Faulting package-relative application ID: 

</details>

**System**

- Czkawka/Krokiet version: 7.0.0 gui and earlier
- OS version: Windows 10 Pro 64-bit
- Installation method: Extract files from zip.

**Comment by EvocativeOlash** [comment] 2024-08-22 08:16
Yes this has been happening to me on windows for all the releases I've tried.

**Comment by qarmin** [comment] 2024-09-30 17:47
Duplicate of https://github.com/qarmin/czkawka/issues/967

**Closed by qarmin** 2024-09-30 17:47 UTC
Labels: bug
