### ISSUE TITLE
Preview of images

### ISSUE THREAD

**Issue by Bagerian** [qarmin/czkawka#423] opened 2021-08-18 10:20 UTC
Please allow moving image preview to the left side (area marked in red https://i.imgur.com/P01gnQ9.png) and also allow making it bigger/smaller. 
Thanks!

**Comment by qarmin** [comment] 2021-11-25 10:09
Duplicate of #142
Part with moving image to left side can't be done, because it when opening preview of any image, results would move from left side to right

**Closed by qarmin** 2021-11-25 10:09 UTC
