### ISSUE TITLE
Unable to delete within similar videos screen

### ISSUE THREAD

**Issue by deadbeatdandylyon** [qarmin/czkawka#1063] opened 2023-09-20 23:59 UTC
When I scan for "Similar Videos" 

And it finds a comparison, when I put a check mark in one of the videos to delete and press delete nothing happens.

Not sure what to do about this? or if this is a known issue? 

Thank you for the help in advanced.

**Comment by mariolos** [comment] 2023-09-25 19:38
The same issue for me.

**Comment by qarmin** [comment] 2023-10-07 16:10
Duplicate of https://github.com/qarmin/czkawka/issues/1009 - fixed already in master branch, new version will be available soon

**Closed by qarmin** 2023-10-07 16:10 UTC
