### ISSUE TITLE
Music Duplicates - Length matching excludes valid duplicates

### ISSUE THREAD

**Issue by kaysond** [qarmin/czkawka#697] opened 2022-04-27 22:15 UTC
I'm running 4.1.0 on Windows Server 2k19. I have about 20k mp3s that I'm scanning for duplicates. When I just do `Title` and `Artist`, I get about 4000 duplicates, most of which are correctly duplicates. However, there are a few cases where artist and track names are similar or identical, but they are different tracks. This would be resolved by also checking that the length is the same.

However, when I enable length checking, the number of duplicates drops from 4000 to about 20. It seems that the code is checking the `length` tag, and I've confirmed that these are exactly the same for a number of cases in my library. Not sure why it's breaking the dupe detection.

**Comment by qarmin** [comment] 2022-04-28 13:43
This is expected behavior, because only not empty tags can be compared with each other.
This should be mostly fixed by https://github.com/qarmin/czkawka/pull/698, because it fill more length in more files.

**Closed by qarmin** 2022-04-28 13:43 UTC

**Comment by kaysond** [comment] 2022-04-28 16:51
Thanks! Will also test this when the next release happens
