### ISSUE TITLE
linux_czkawka_gui crashes if Sort is selected with any option

### ISSUE THREAD

**Issue by aloboa** [qarmin/czkawka#1266] opened 2024-04-11 06:52 UTC
**Bug Description**
Sort makes linux_czkawka_gui crash

**Steps to reproduce:**

Once duplicates have been found, click on Sort and any of the 4 options. The program crashes

**Terminal output** (optional):
```
$ ./linux_czkawka_gui 
22:08:25.878 [INFO] czkawka_core::common: App version: 7.0.0, release mode, rust 1.76.0 (2024-02-04), os Pop!_OS 22.04 [x86_64 64-bit], 8 cpu/threads
22:08:26.210 [INFO] czkawka_gui: Set thread number to 8
22:08:30.107 [INFO] czkawka_core::duplicate: find_duplicates
22:08:30.239 [INFO] czkawka_core::duplicate: find_duplicates: Done in 131.93ms

(linux_czkawka_gui:8945): Gtk-CRITICAL **: 22:08:33.714: gtk_list_store_get_value: assertion 'iter_is_valid (iter, list_store)' failed
thread 'main' panicked at /home/runner/.cargo/registry/src/index.crates.io-6f17d22bba15001f/gtk4-0.8.0/src/tree_model.rs:49:14:
Failed to get TreeModel value: ValueTypeMismatchError { actual: <invalid>, requested: gboolean }
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
-->

<details>
<summary>Debug log</summary>

# UNCOMMENT DETAILS AND PUT LOGS HERE

</details>
```

**System**

- Czkawka/Krokiet version: rust 1.76.0 (2024-02-04)
- OS version: linux Pop!_OS 22.04
- Installation method: [binary ](https://github.com/qarmin/czkawka/releases/download/7.0.0/linux_czkawka_cli)

**Comment by qarmin** [comment] 2024-09-30 18:27
Duplicate of https://github.com/qarmin/czkawka/issues/1116

**Closed by qarmin** 2024-09-30 18:27 UTC
Labels: bug
