### ISSUE TITLE
Preview in 'Similar Images' stuck

### ISSUE THREAD

**Issue by goodboi69** [qarmin/czkawka#166] opened 2020-12-30 16:26 UTC
Issue 1: The last image clicked stays as a preview.

Fix: The image should disappear.

Issue 2: Clicking on a search result and using the arrow keys, the image preview is stuck. The preview only changes when clicked by the mouse.

Fix: The image preview should change to the highlighted one via keys.

![Untitled-1](https://user-images.githubusercontent.com/43517545/103366976-ec4b4000-4a91-11eb-85e2-cfdc233d5231.jpg)

**Comment by qarmin** [comment] 2020-12-31 09:12
Second issue is duplicate of https://github.com/qarmin/czkawka/issues/143

**Closed** 2020-12-31 09:12 UTC
Labels: bug
