### ISSUE TITLE
Feature request PNG preview in similar images compare

### ISSUE THREAD

**Issue by astandarduser** [qarmin/czkawka#778] opened 2022-07-17 02:44 UTC
It would be nice to have a PNG preview in similar images compare, all jpg's have one

**Comment by qarmin** [comment] 2022-07-19 19:09
All image files should have preview(maybe except .exr and other exotic extensions).
Which exactly images have no preview?

**Comment by kurumushi** [comment] 2022-07-27 10:03
I've noticed that at least on linux, if a file ends in .PNG instead of .png, the file will not show in previews, so maybe it's a case sensitivity issue.

**Comment by qarmin** [comment] 2022-07-27 10:56
So looks that this is duplicate of https://github.com/qarmin/czkawka/issues/723 and is already fixed in master

**Closed by qarmin** 2022-07-27 10:56 UTC
