### ISSUE TITLE
Program crashes when pasting path in "Manual Add"

### ISSUE THREAD

**Issue by inger147** [qarmin/czkawka#1144] opened 2023-11-22 20:30 UTC
**Desktop (please complete the following information):**

- Czkawka version: 5.1.0, 6.0.0
- OS version: Windows 10

**Bug Description**

In Similar Videos: The Program crashes when pasting path in "Manual Add".  To work around this I need to browse to a folder using the "Add" button.

**Comment by qarmin** [comment] 2023-11-22 21:21
Duplicate of https://github.com/qarmin/czkawka/issues/1044

**Closed by qarmin** 2023-11-22 21:21 UTC
Labels: bug
