### ISSUE TITLE
"Select" controls not working

### ISSUE THREAD

**Issue by groundcontroldp** [qarmin/czkawka#994] opened 2023-06-11 21:15 UTC
Hi, I have the latest GTK4 on an intel mac and the select controls do not seem to be working for me. I can individually select images but using the select button does nothing at all.

**Comment by qarmin** [comment] 2023-06-12 07:37
Duplicate of https://github.com/qarmin/czkawka/issues/979 
If you are using latest gtk version and if this is gtk regression, you can try to install GTK 4.8 or 4.6 (looks like homebrew allows to do this)

**Closed by qarmin** 2023-06-12 07:37 UTC
