### ISSUE TITLE
Crash | Too many duplicate files cause it?

### ISSUE THREAD

**Issue by Illegal-Services** [qarmin/czkawka#589] opened 2022-01-17 10:35 UTC
I've been using the app on 5251 files, it found a lot of duplicates from there, and the app analyzed successfully all duplicates.
But when it come to "select all duplicates except oldest", then the app immediately crash once I click the "delete" button.
I wish to help in any ways, so if I can do anything to help the developper fix that crash, let me know what to do.

**Comment by qarmin** [comment] 2022-01-17 10:59
App can handle even hundreds of thousands of records, so this is not a problem.
Which exactly version was used?
If <3.3.0, then such crashes are expected and probably were fixed in new versions
If 3.3.0 or 3.3.1, then I see only 2 places where it could happens - selecting all results or reversing selection (https://github.com/qarmin/czkawka/commit/6db372ec5ebb8bc3edf2d2ce819f861c019469e8)

The problem is probably fixed in master branch(and unreleased 3.3.2 version) so I suggest to test the latest available binaries from e.g. this link - https://github.com/qarmin/czkawka/actions/runs/1704767415

**Comment by Illegal-Services** [comment] 2022-01-17 11:08
Thank you so much for the quick answer.
i've downloaded this one because I'm under Windows:
https://github.com/qarmin/czkawka/suites/4954013166/artifacts/143891181

And it work just fine now. Great app, keep it up:)

**Comment by Jacques-F** [comment] 2022-01-18 09:28
Hi,
I have the same problem in a directory.
Result of the search : Found 2066 duplicated files which in 641 groups which takes 5.19 GiB.
This the backtrace when I click on Hardlink button whith only 2 files selected:
================================================================================
[jacques@jacques ~]$ export env RUST_BACKTRACE=full
[jacques@jacques ~]$ /home/jacques/bin/AppImage/linux_czkawka_gui.AppImage
Gtk-Message: 10:22:01.175: Failed to load module "colorreload-gtk-module"
Gtk-Message: 10:22:01.177: Failed to load module "window-decorations-gtk-module"
thread 'main' panicked at 'index out of bounds: the len is 0 but the index is 0', czkawka_gui/src/connect_button_hardlink.rs:109:50
stack backtrace:
   0:     0x561989f2b1fc - std::backtrace_rs::backtrace::libunwind::trace::h3fea1eb2e0ba2ac9
                               at /rustc/59eed8a2aac0230a8b53e89d4e99d55912ba6b35/library/std/src/../../backtrace/src/backtrace/libunwind.rs:90:5
   1:     0x561989f2b1fc - std::backtrace_rs::backtrace::trace_unsynchronized::h849d83492cbc0d59
                               at /rustc/59eed8a2aac0230a8b53e89d4e99d55912ba6b35/library/std/src/../../backtrace/src/backtrace/mod.rs:66:5
   2:     0x561989f2b1fc - std::sys_common::backtrace::_print_fmt::he3179d37290f23d3
                               at /rustc/59eed8a2aac0230a8b53e89d4e99d55912ba6b35/library/std/src/sys_common/backtrace.rs:67:5
   3:     0x561989f2b1fc - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::h140f6925cad14324
                               at /rustc/59eed8a2aac0230a8b53e89d4e99d55912ba6b35/library/std/src/sys_common/backtrace.rs:46:22
   4:     0x561989f52a4c - core::fmt::write::h31b9cd1bedd7ea38
                               at /rustc/59eed8a2aac0230a8b53e89d4e99d55912ba6b35/library/core/src/fmt/mod.rs:1150:17
   5:     0x561989f270c5 - std::io::Write::write_fmt::h1fdf66f83f70913e
                               at /rustc/59eed8a2aac0230a8b53e89d4e99d55912ba6b35/library/std/src/io/mod.rs:1667:15
   6:     0x561989f2d1e0 - std::sys_common::backtrace::_print::he7ac492cd19c3189
                               at /rustc/59eed8a2aac0230a8b53e89d4e99d55912ba6b35/library/std/src/sys_common/backtrace.rs:49:5
   7:     0x561989f2d1e0 - std::sys_common::backtrace::print::hba20f8920229d8e8
                               at /rustc/59eed8a2aac0230a8b53e89d4e99d55912ba6b35/library/std/src/sys_common/backtrace.rs:36:9
   8:     0x561989f2d1e0 - std::panicking::default_hook::{{closure}}::h714d63979ae18678
                               at /rustc/59eed8a2aac0230a8b53e89d4e99d55912ba6b35/library/std/src/panicking.rs:210:50
   9:     0x561989f2cd97 - std::panicking::default_hook::hf1afb64e69563ca8
                               at /rustc/59eed8a2aac0230a8b53e89d4e99d55912ba6b35/library/std/src/panicking.rs:227:9
  10:     0x561989f2d894 - std::panicking::rust_panic_with_hook::h02231a501e274a13
                               at /rustc/59eed8a2aac0230a8b53e89d4e99d55912ba6b35/library/std/src/panicking.rs:624:17
  11:     0x561989f2d370 - std::panicking::begin_panic_handler::{{closure}}::h5b5e738edf361af7
                               at /rustc/59eed8a2aac0230a8b53e89d4e99d55912ba6b35/library/std/src/panicking.rs:521:13
  12:     0x561989f2b6c4 - std::sys_common::backtrace::__rust_end_short_backtrace::h601a115def7987b1
                               at /rustc/59eed8a2aac0230a8b53e89d4e99d55912ba6b35/library/std/src/sys_common/backtrace.rs:141:18
  13:     0x561989f2d2d9 - rust_begin_unwind
                               at /rustc/59eed8a2aac0230a8b53e89d4e99d55912ba6b35/library/std/src/panicking.rs:517:5
  14:     0x561989c49921 - core::panicking::panic_fmt::h7a58c8fffc5559a4
                               at /rustc/59eed8a2aac0230a8b53e89d4e99d55912ba6b35/library/core/src/panicking.rs:101:14
  15:     0x561989c498e2 - core::panicking::panic_bounds_check::h7e4a875efe91e705
                               at /rustc/59eed8a2aac0230a8b53e89d4e99d55912ba6b35/library/core/src/panicking.rs:77:5
  16:     0x561989cd465a - czkawka_gui::connect_button_hardlink::hardlink_symlink::he23fef646965bf58
  17:     0x561989c666b9 - <O as gtk::auto::button::ButtonExt>::connect_clicked::clicked_trampoline::h1856801f3d2cf748
  18:     0x7f5ffdd222f6 - <unknown>
  19:     0x7f5ffdd3d9df - g_signal_emit_valist
  20:     0x7f5ffdd3e10f - g_signal_emit
  21:     0x7f5ffd509add - <unknown>
  22:     0x7f5ffd509b35 - <unknown>
  23:     0x7f5ffdd222f6 - <unknown>
  24:     0x7f5ffdd3d9df - g_signal_emit_valist
  25:     0x7f5ffdd3e10f - g_signal_emit
  26:     0x7f5ffd507f90 - <unknown>
  27:     0x7f5ffbce7dae - ffi_call_unix64
  28:     0x7f5ffbce771f - ffi_call
  29:     0x7f5ffdd22c9d - g_cclosure_marshal_generic_va
  30:     0x7f5ffdd222f6 - <unknown>
  31:     0x7f5ffdd3d9df - g_signal_emit_valist
  32:     0x7f5ffdd3e10f - g_signal_emit
  33:     0x7f5ffd5c4a36 - <unknown>
  34:     0x7f5ffdd24fb8 - g_cclosure_marshal_VOID__BOXEDv
  35:     0x7f5ffdd222f6 - <unknown>
  36:     0x7f5ffdd3d9df - g_signal_emit_valist
  37:     0x7f5ffdd3e10f - g_signal_emit
  38:     0x7f5ffd5c1d0e - <unknown>
  39:     0x7f5ffd5c32fb - <unknown>
  40:     0x7f5ffd5c5f5e - <unknown>
  41:     0x7f5ffd593721 - gtk_event_controller_handle_event
  42:     0x7f5ffd75326b - <unknown>
  43:     0x7f5ffd60d8f7 - <unknown>
  44:     0x7f5ffdd222f6 - <unknown>
  45:     0x7f5ffdd3d3ad - g_signal_emit_valist
  46:     0x7f5ffdd3e10f - g_signal_emit
  47:     0x7f5ffd755534 - <unknown>
  48:     0x7f5ffd60a86e - <unknown>
  49:     0x7f5ffd60c948 - gtk_main_do_event
  50:     0x7f5ffd113765 - <unknown>
  51:     0x7f5ffd143f92 - <unknown>
  52:     0x7f5ffc2849be - g_main_context_dispatch
  53:     0x7f5ffc284d18 - <unknown>
  54:     0x7f5ffc28500b - g_main_loop_run
  55:     0x7f5ffd60ba25 - gtk_main
  56:     0x561989cad06d - czkawka_gui::main::h2da3c263011fa181
  57:     0x561989c86d73 - std::sys_common::backtrace::__rust_begin_short_backtrace::h28d1a0e8b2e95a89
  58:     0x561989ca50a9 - std::rt::lang_start::{{closure}}::h5d3094b3f0243912
  59:     0x561989f2de9a - core::ops::function::impls::<impl core::ops::function::FnOnce<A> for &F>::call_once::h2790017aba790142
                               at /rustc/59eed8a2aac0230a8b53e89d4e99d55912ba6b35/library/core/src/ops/function.rs:259:13
  60:     0x561989f2de9a - std::panicking::try::do_call::hd5d0fbb7d2d2d85d
                               at /rustc/59eed8a2aac0230a8b53e89d4e99d55912ba6b35/library/std/src/panicking.rs:403:40
  61:     0x561989f2de9a - std::panicking::try::h675520ee37b0fdf7
                               at /rustc/59eed8a2aac0230a8b53e89d4e99d55912ba6b35/library/std/src/panicking.rs:367:19
  62:     0x561989f2de9a - std::panic::catch_unwind::h803430ea0284ce79
                               at /rustc/59eed8a2aac0230a8b53e89d4e99d55912ba6b35/library/std/src/panic.rs:129:14
  63:     0x561989f2de9a - std::rt::lang_start_internal::{{closure}}::h3a398a8154de3106
                               at /rustc/59eed8a2aac0230a8b53e89d4e99d55912ba6b35/library/std/src/rt.rs:45:48
  64:     0x561989f2de9a - std::panicking::try::do_call::hf60f106700df94b2
                               at /rustc/59eed8a2aac0230a8b53e89d4e99d55912ba6b35/library/std/src/panicking.rs:403:40
  65:     0x561989f2de9a - std::panicking::try::hb2022d2bc87a9867
                               at /rustc/59eed8a2aac0230a8b53e89d4e99d55912ba6b35/library/std/src/panicking.rs:367:19
  66:     0x561989f2de9a - std::panic::catch_unwind::hbf801c9d61f0c2fb
                               at /rustc/59eed8a2aac0230a8b53e89d4e99d55912ba6b35/library/std/src/panic.rs:129:14
  67:     0x561989f2de9a - std::rt::lang_start_internal::hdd488b91dc742b96
                               at /rustc/59eed8a2aac0230a8b53e89d4e99d55912ba6b35/library/std/src/rt.rs:45:20
  68:     0x561989cad632 - main
  69:     0x7f5ffbf12e1a - __libc_start_main
  70:     0x561989c4a0fa - _start
  71:                0x0 - <unknown>
================================================================================

**Closed** 2022-01-19 13:27 UTC
