### ISSUE TITLE
Pressing "Search" again while viewing duplicates freezes UI

### ISSUE THREAD

**Issue by AndreiMiculita** [qarmin/czkawka#838] opened 2022-09-19 12:02 UTC
Czkawka Flatpak v5.0.2
Linux Mint 20.3 Cinnamon

1. Open Czkawka and select /home/username folder (mine's about 250GB)
2. Select "Duplicate files" from the sidebar and click the "Search" button
3. Wait for it to finish (there will be a popup showing progress)
4. Delete some duplicate files manually (i.e. open them from the File Explorer and send them to Trash, or use `rm` from the terminal
5. Got back to Czkawka and press "Search" again 
6. UI freezes

There is no popup showing progress. Not sure if there is a scan happening, but I've left it on for about 20 mins and it hasn't finished.

There should either be a popup showing the (re)scan progress (if that's what's happening) or otherwise, the "Search" button label should change. The UI is also completely unresponsive and I had to just force quit the program.

**Comment by qarmin** [comment] 2022-09-24 17:49
I cannot reproduce this now, but I remember that sometimes when clicking scan button, UI froze and backtrace showed that it froze inside GTK code.

App only add values to treeview when scan ends, clear entire model when scan starts or remove single records when used delete/modify results, so no strange or advanced things are done here.

So it looks like this is a bug on the GTK side, which I doubt will be fixed in the near future, since GtkTreeview, which Czkawka uses, is rather unsupported(I will try in future to check posibility to use ColumnView)

**Comment by AndreiMiculita** [comment] 2022-09-26 10:09
Thank you for looking into it! It might help to change the label of the "Search" button to "Search again" (or if it were "Scan" and then "Rescan") to make it clearer that, in fact, the search is happening again; even if it freezes, at least I have some clearer messages.

In my opinion, it should also be somewhere higher up; there are very few cases in which a UI would should the result of an operation above the button that triggers said operation.

**Comment by qarmin** [comment] 2024-01-14 14:14
Looks like same problem like https://github.com/qarmin/czkawka/issues/1110 and workaround already was applied

**Closed by qarmin** 2024-01-14 14:14 UTC
Labels: bug
