### ISSUE TITLE
Find similar videos crashes if you select move files, hangs if you select delete 

### ISSUE THREAD

**Issue by willhubs** [qarmin/czkawka#1071] opened 2023-10-04 21:23 UTC
Fresh install of Ubuntu 22.04.3, czkawka 6.0.0, deleting duplicate files works as expected, deleting empty directories works as expected.

Found lots of video files that were a match, went through the entire list and selected all relevant similar videos and choose delete, nothing happens.  Then choose move, select directory to move to(to eventually delete the entire directory) and it crashes instantly.  Started the program again, tried again this time selecting just one similar video and the same thing happened.

**Comment by willhubs** [comment] 2023-10-04 22:24
Not sure if this helps, same error in the terminal regardless of move or delete.


Set thread number to 12
thread 'main' panicked at 'assertion failed: model.get::<bool>(&iter, column_header)', czkawka_gui/src/help_functions.rs:558:13

**Comment by qarmin** [comment] 2023-10-07 16:10
Duplicate of https://github.com/qarmin/czkawka/issues/1009 - fixed already in master branch, new version will be available soon

**Closed by qarmin** 2023-10-07 16:10 UTC
