### ISSUE TITLE
similar videos is broking

### ISSUE THREAD

**Issue by timeg7100** [qarmin/czkawka#1062] opened 2023-09-18 12:39 UTC
hi
the similar videos can't move files every time i try the app closes

**Comment by mariolos** [comment] 2023-09-25 19:38
The same issue for me.

**Comment by qarmin** [comment] 2023-10-07 16:10
Duplicate of https://github.com/qarmin/czkawka/issues/1009 - fixed already in master branch, new version will be available soon

**Closed by qarmin** 2023-10-07 16:10 UTC
